import type { components } from './generated/api-types';

export type { components };
export type Region = components['schemas']['RegionDto'];
export type Sector = components['schemas']['SectorDto'];
export type Route = components['schemas']['RouteDto'];
export type GradeScale = Route['gradeScale'];
export type GradeHistogramGroup =
  components['schemas']['GradeHistogramGroupDto'];
export type GradeCount = components['schemas']['GradeCountDto'];
export type ClimbType = GradeHistogramGroup['type'];
export type RouteGradeScale = NonNullable<Me['gradeScaleRoute']>;
export type BoulderGradeScale = NonNullable<Me['gradeScaleBoulder']>;
export type Tick = components['schemas']['TickDto'];
export type CreateTick = components['schemas']['CreateTickDto'];
export type UpdateTick = components['schemas']['UpdateTickDto'];
export type TickFeedPage = components['schemas']['TickFeedPageDto'];
export type TickPage = components['schemas']['TickPageDto'];
export type TickStats = components['schemas']['TickStatsDto'];
export type TickGradeCount = components['schemas']['TickGradeCountDto'];
export type GradeOpinion = NonNullable<Tick['gradeOpinion']>;
export type TickMedia = components['schemas']['TickMediaDto'];
export type UserSummary = components['schemas']['UserSummaryDto'];
export type Me = components['schemas']['MeDto'];
export type UpdateMe = components['schemas']['UpdateMeDto'];
export type ClimberContent = components['schemas']['ClimberContentDto'];
export type Topo = components['schemas']['TopoDto'];
export type RouteComment = components['schemas']['CommentDto'];
export type CreateRouteComment = components['schemas']['CreateCommentDto'];
export type UpdateRouteComment = components['schemas']['UpdateCommentDto'];
export type RouteMedia = components['schemas']['MediaDto'];
export type CreateRouteMedia = components['schemas']['CreateMediaDto'];
export type RouteLine = components['schemas']['RouteLineDto'];
export type UpdateRegion = components['schemas']['UpdateRegionDto'];
export type CreateRegion = components['schemas']['CreateRegionDto'];
export type UpdateSector = components['schemas']['UpdateSectorDto'];
export type CreateSector = components['schemas']['CreateSectorDto'];
export type UpdateRoute = components['schemas']['UpdateRouteDto'];
export type CreateRoute = components['schemas']['CreateRouteDto'];
export type ReorderTopos = components['schemas']['ReorderToposDto'];
export type TopoOrder = components['schemas']['TopoOrderDto'];
export type SaveRouteLine = components['schemas']['SaveRouteLineDto'];
