import type { components } from './generated/api-types';

export type { components };
export type Region = components['schemas']['RegionDto'];
export type Sector = components['schemas']['SectorDto'];
export type Route = components['schemas']['RouteDto'];
export type GradeScale = Route['gradeScale'];
export type RouteGradeScale = NonNullable<Me['gradeScaleRoute']>;
export type BoulderGradeScale = NonNullable<Me['gradeScaleBoulder']>;
export type Tick = components['schemas']['TickDto'];
export type CreateTick = components['schemas']['CreateTickDto'];
export type Me = components['schemas']['MeDto'];
export type UpdateMe = components['schemas']['UpdateMeDto'];
export type Topo = components['schemas']['TopoDto'];
export type RouteComment = components['schemas']['CommentDto'];
export type CreateRouteComment = components['schemas']['CreateCommentDto'];
export type RouteMedia = components['schemas']['MediaDto'];
export type CreateRouteMedia = components['schemas']['CreateMediaDto'];
export type RouteLine = components['schemas']['RouteLineDto'];
export type UpdateRegion = components['schemas']['UpdateRegionDto'];
export type UpdateSector = components['schemas']['UpdateSectorDto'];
export type UpdateRoute = components['schemas']['UpdateRouteDto'];
export type CreateRoute = components['schemas']['CreateRouteDto'];
export type UpdateTopo = components['schemas']['UpdateTopoDto'];
export type ReorderTopos = components['schemas']['ReorderToposDto'];
export type TopoOrder = components['schemas']['TopoOrderDto'];
export type SaveRouteLine = components['schemas']['SaveRouteLineDto'];
